### ISSUE TITLE
Some possible false positives

### ISSUE THREAD

**Issue by ice1000** [JetBrains/intellij-plugin-verifier#10]
I'm getting these errors:

![Screenshot from 2019-04-17 19-30-48](https://user-images.githubusercontent.com/16398479/56327202-5fd6dd80-6147-11e9-98b0-e2aa2e9c7b77.png)
![Screenshot from 2019-04-17 19-30-56](https://user-images.githubusercontent.com/16398479/56327203-5fd6dd80-6147-11e9-858f-da81791c3a5c.png)

However, those classes **are** present in JRE (in both JRE 8 and JRE 11):

+ JRE 11
  + https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/Buffer.html#position(int)
  + https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/ByteBuffer.html
+ JRE 8
  + https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html
  + https://docs.oracle.com/javase/8/docs/api/java/nio/Buffer.html#position-int-

**Comment by serejke** [comment]
Hello, @ice1000.
Thank you for reporting the issue!

Access to unresolved class `()I`, `(I)J` and similar are indeed bugs caused by incorrect verification of [LDC](https://docs.oracle.com/javase/specs/jvms/se9/html/jvms-5.html#jvms-5.4.3.5) instruction for a case when its operand is `MethodHandle` or `MethodType`, which is `()I`, `(I)J` and so on. The verifier used to treat them like a class reference. It is going to be fixed soon and your plugin re-verified.

As for the `ByteBuffer.position(int)`, it turned out to be quite tricky to investigate but I suppose it is a correct warning. For some reason in bytecode of your classes was written an incorrect method descriptor:
`invokevirtual java/nio/ByteBuffer.position:(I)Ljava/nio/ByteBuffer;`
instead of
`invokevirtual java/nio/ByteBuffer.position:(I)Ljava/nio/Buffer;`

note that the only difference is in return type. But for JVM it is essential because it always resolves the method with exactly the same descriptor. And in `ByteBuffer` there isn't a method with return type of `ByteBuffer` but only the one inherited from `Buffer` with `Buffer` return type.

I suppose this has something to do with obfuscation utility you apparently use.
This problem took place in plugin version 0.2.2 but is not the case for 0.2.4 anymore, so the latest version is perfectly compatible with all targeted IDE builds.

**Comment by ice1000** [comment]
Thanks, I'll take a look!
