### ISSUE TITLE
Missing verifier-all.jar for some versions on Bintray

### ISSUE THREAD

**Issue by halirutan** [JetBrains/intellij-plugin-verifier#14]
I noticed that the `curl` call given in the main README left me with a "corrupted" `verifier-all.jar`. Indeed, when you look in the [1.214 version on Bintray](https://dl.bintray.com/jetbrains/intellij-plugin-service/org/jetbrains/intellij/plugins/verifier-cli/1.214/) there is no such file. In version 1.210 the `verifier-all.jar` exists but in later versions it doesn't.

**Comment by serejke** [comment]
Hello, @halirutan, 
Thank you for reporting this problem. 
Unfortunately, I didn't notice the new issue because of incorrect notification settings. Sorry for the delayed response.

Indeed, after some change in `build.gradle`, the `verifier-all.jar` ceased to be published to Bintray. I hope you have found a way to overcome that: either used a previous version, or built the verifier from sources.

Now the `build.gradle` is fixed and the `curl` command from README works as expected.
